-- MySQL Script generated by MySQL Workbench
-- Mon Jun  8 16:41:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sapposstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sapposstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sapposstore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sapposstore` ;

-- -----------------------------------------------------
-- Table `sapposstore`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_clientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `id-rol` INT NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `id_rol_idx` (`id-rol` ASC) VISIBLE,
  CONSTRAINT `id_rol`
    FOREIGN KEY (`id-rol`)
    REFERENCES `sapposstore`.`rol` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ventas`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `sapposstore`.`clientes` (`id_clientes`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sapposstore`.`usuarios` (`id_usuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NULL,
  `precio_compra` DECIMAL(10,2) NULL DEFAULT NULL,
  `precio_venta` DECIMAL(10,2) NULL DEFAULT NULL,
  `utilidad` DECIMAL(10,2) NULL DEFAULT NULL,
  `stock` INT NULL DEFAULT '0',
  `stock_minimo` INT NULL DEFAULT '2',
  `id_categoria` INT NULL DEFAULT NULL,
  `id_provedor` INT NULL DEFAULT NULL,
  `fecha_registro` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `id_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `sapposstore`.`categoria` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`detalle_venta` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_venta` INT NULL DEFAULT NULL,
  `id_producto` INT NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precio_unitario` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `id_venta_idx` (`id_venta` ASC) VISIBLE,
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `id_venta`
    FOREIGN KEY (`id_venta`)
    REFERENCES `sapposstore`.`ventas` (`id_ventas`),
  CONSTRAINT `productos`
    FOREIGN KEY (`id_producto`)
    REFERENCES `sapposstore`.`productos` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`devoluciones` (
  `id_devolucion` INT NOT NULL AUTO_INCREMENT,
  `id_venta` INT NULL DEFAULT NULL,
  `id_producto` INT NULL DEFAULT NULL,
  `motivo` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_devolucion`),
  INDEX `id_ventas_idx` (`id_venta` ASC) VISIBLE,
  CONSTRAINT `ventas`
    FOREIGN KEY (`id_venta`)
    REFERENCES `sapposstore`.`ventas` (`id_ventas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`facturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`facturacion` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `id_ventas` INT NULL DEFAULT NULL,
  `numero_factura` VARCHAR(50) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `impuestos` DECIMAL(10,2) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `id_ventas_idx` (`id_ventas` ASC) VISIBLE,
  CONSTRAINT `id_ventas`
    FOREIGN KEY (`id_ventas`)
    REFERENCES `sapposstore`.`ventas` (`id_ventas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`integraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`integraciones` (
  `id_integraciones` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `api_key` VARCHAR(255) NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT '1',
  PRIMARY KEY (`id_integraciones`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`inventario_movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`inventario_movimiento` (
  `idinventario_movimiento` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NULL DEFAULT NULL,
  `tipo_movimiento` ENUM('ENTRADA', 'SALIDA') NOT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `observacion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idinventario_movimiento`),
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `sapposstore`.`productos` (`id_producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`sincronizacion_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`sincronizacion_stock` (
  `id_sincronizacion` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_integraciones` INT NOT NULL,
  `stock_anterior` INT NOT NULL,
  `stock_actual` INT NOT NULL,
  `fecha_sincronizacion` DATETIME NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sincronizacion`),
  INDEX `fk_sync_producto_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_sync_integraciones_idx` (`estado` ASC) VISIBLE,
  INDEX `fk_sync_integraciones_idx1` (`id_integraciones` ASC) VISIBLE,
  CONSTRAINT `fk_sync_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `sapposstore`.`productos` (`id_producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sync_integraciones`
    FOREIGN KEY (`id_integraciones`)
    REFERENCES `sapposstore`.`integraciones` (`id_integraciones`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`stock_alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`stock_alerta` (
  `idalerta_stock` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NULL DEFAULT NULL,
  `mensaje` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `atendida` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`idalerta_stock`),
  INDEX `fk_alerta_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_alerta_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `sapposstore`.`productos` (`id_producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sapposstore`.`venta_integraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapposstore`.`venta_integraciones` (
  `idventa_integraciones` INT NOT NULL AUTO_INCREMENT,
  `id_integraciones` INT NULL DEFAULT NULL,
  `codigo_externo` VARCHAR(100) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idventa_integraciones`),
  INDEX `id_integraciones_idx` (`id_integraciones` ASC) VISIBLE,
  CONSTRAINT `id_integraciones`
    FOREIGN KEY (`id_integraciones`)
    REFERENCES `sapposstore`.`integraciones` (`id_integraciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
